# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(db_index=True, verbose_name='Начало действия')),
                ('end', models.DateField(db_index=True, verbose_name='Окончание действия')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма накоплений для скидки')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Проценты бонусов')),
            ],
            options={
                'verbose_name': 'Политика начисление бонусов',
                'verbose_name_plural': 'Политики начисления бонусов',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Имя')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('card', models.TextField(db_index=True, unique=True, verbose_name='Номер карты')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Бонусный счет')),
                ('created', models.DateTimeField(db_index=True, verbose_name='Создан')),
                ('hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма')),
                ('summa_sale', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма скидки')),
                ('summa_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Получено бонусов')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Service', verbose_name='Услуга'),
        ),
    ]
