# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Информационное значение',
                'ordering': ['code'],
                'verbose_name_plural': 'Информационные значения',
            },
        ),
    ]
