# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 19:19
from __future__ import unicode_literals

from django.db import migrations
from datetime import date


def create(apps, *args, **kwargs):
    BonusPolicy = apps.get_model('accounting', 'BonusPolicy')
    BonusPolicy(
        begin=date(2000, 1, 1),
        end=date(2080, 1, 1),
        limit=100,
        percent=4).save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_infovar'),
    ]

    operations = [
        migrations.RunPython(create)
    ]
